### ISSUE TITLE
Submit a PR to the opportunity.census.gov with Hawaii data sets

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/organization#150]
Add a yml file to https://github.com/uscensusbureau/opportunity/tree/master/_data/data-providers

Example:

```
name: "Washington, DC"
url: "https://opendata.dc.gov"
datasets:
  - topic: "Parcels and addresses"
    description: "Snow removal route"
    url: "http://opendata.dc.gov/datasets/a0491c3eb8224c1a99a3552a0c1d97ed_20"

  - topic: "Permits"
    description: "Construction permits"
    url: "http://opendata.dc.gov/datasets/fc7da7bd29d4493481b17d032e117d09_0"
```
